[2022-03-17 03:22:25,800] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: testing_dag.ingest 2019-09-02T06:00:00+00:00 [queued]>
[2022-03-17 03:22:25,835] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: testing_dag.ingest 2019-09-02T06:00:00+00:00 [queued]>
[2022-03-17 03:22:25,837] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 03:22:25,839] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-17 03:22:25,840] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 03:22:25,863] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): ingest> on 2019-09-02T06:00:00+00:00
[2022-03-17 03:22:25,870] {standard_task_runner.py:52} INFO - Started process 1044 to run task
[2022-03-17 03:22:25,879] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_dag', 'ingest', '2019-09-02T06:00:00+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmp0ws5vcu9', '--error-file', '/tmp/tmp1q7_g5nz']
[2022-03-17 03:22:25,885] {standard_task_runner.py:77} INFO - Job 24: Subtask ingest
[2022-03-17 03:22:25,983] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_dag.ingest 2019-09-02T06:00:00+00:00 [running]> on host 509d5aa4e827
[2022-03-17 03:22:26,087] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_dag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-17 03:22:26,090] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-17 03:22:26,094] {bash.py:158} INFO - Running command: ls /opt/airflow
[2022-03-17 03:22:26,106] {bash.py:169} INFO - Output:
[2022-03-17 03:22:26,169] {bash.py:173} INFO - airflow.cfg
[2022-03-17 03:22:26,171] {bash.py:173} INFO - dags
[2022-03-17 03:22:26,172] {bash.py:173} INFO - google_credentials.json
[2022-03-17 03:22:26,174] {bash.py:173} INFO - logs
[2022-03-17 03:22:26,176] {bash.py:173} INFO - output_2019-01.csv
[2022-03-17 03:22:26,177] {bash.py:173} INFO - output_2019-02.csv
[2022-03-17 03:22:26,179] {bash.py:173} INFO - output_2019-03.csv
[2022-03-17 03:22:26,180] {bash.py:173} INFO - output_2019-04.csv
[2022-03-17 03:22:26,182] {bash.py:173} INFO - output_2019-05.csv
[2022-03-17 03:22:26,183] {bash.py:173} INFO - output_2019-06.csv
[2022-03-17 03:22:26,184] {bash.py:173} INFO - output_2019-07.csv
[2022-03-17 03:22:26,185] {bash.py:173} INFO - output_2019-08.csv
[2022-03-17 03:22:26,186] {bash.py:173} INFO - output_2019-09.csv
[2022-03-17 03:22:26,188] {bash.py:173} INFO - plugins
[2022-03-17 03:22:26,189] {bash.py:173} INFO - unittests.cfg
[2022-03-17 03:22:26,190] {bash.py:173} INFO - webserver_config.py
[2022-03-17 03:22:26,191] {bash.py:177} INFO - Command exited with return code 0
[2022-03-17 03:22:26,237] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=ingest, execution_date=20190902T060000, start_date=20220317T032225, end_date=20220317T032226
[2022-03-17 03:22:26,290] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-17 03:22:26,335] {local_task_job.py:146} INFO - Task exited with return code 0
